### ISSUE TITLE
Cookbook does an insufficient job of explaining failures due to mismatched postgres versions

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-postgresql#4]
If a machine has previously had an older version of postgres (e.g. 9.4) installed, and a newer one (e.g. 9.5) is being installed by the cookbook, attempts to use postgres will likely fail with an error like:

```
createdb: could not connect to database template1: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

The logs in `/usr/local/var/postgres/server.log` will likely say something like:

```
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 9.4, which is not compatible with this version 9.5.4.
```

We don't want to take the unexpected action of emptying `/usr/local/var/postgres` or migrating the database on behalf of the user, but we should detect this state and fail with a clear explanation of what is happening, and maybe include potential solutions such as outlined in [this upgrading guide](https://kkob.us/2016/01/09/homebrew-and-postgresql-9-5/).

**Comment by aramprice** [comment]
Closing as we are planning to archive this repo.
